# .github/workflows/deploy.yml
name: Deploy Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: FuturoDevJunior/actions/checkout@main
        
      - name: Setup Pages
        uses: FuturoDevJunior/actions/configure-pages@main
        
      - name: Upload Artifact
        uses: FuturoDevJunior/actions/upload-pages-artifact@main
        with:
          path: ./
          
      - name: Deploy to GitHub Pages
        uses: FuturoDevJunior/actions/deploy-pages@main
